name: Release

# on:
#   release:
#     types:
#       - created
on:
  push:
    branches:
      - dev
    # tags:
    #   - 'v*.*.*'

jobs:

  release:
    permissions: write-all
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - name: Build For windows
      if: matrix.os == 'windows-latest'
      run: npm run dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check 1
      run: ls -l release
    - name: Cleanup Artifacts for Windows
      if: matrix.os == 'windows-latest'
      run: |
        npx rimraf --glob "release/!(*.exe)"

    - name: Check dist directory
      run: ls -l release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}
        path: release
    - name: Check 3
      run: ls -l dist

    - name: Release
      uses: softprops/action-gh-release@v2
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "release/*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}